### ISSUE TITLE
Aggressive Delete in Architecture View

### ISSUE THREAD

**Issue by JimnyCricket** [dfst/deepforge#206]
In the Architecture editor, when a layer is deleted in the middle of an architecture all those below it are also deleted. I think we will want to change this, in the case that someone wants to change out a layer (like SpatialConvolution for SpatialConvolutionMM) without losing the rest of the architecture.

**Comment by brollb** [comment]
Fixed as of https://github.com/dfst/deepforge/commit/552e71687da82ca958443a1c8c4446c0ee05a0ba
