### ISSUE TITLE
Double Click when Loading Project causes error

### ISSUE THREAD

**Issue by JimnyCricket** [dfst/deepforge#231]
When choosing a project on startup there can be a delay in loading the project. Clicking a project doesn't provide instant feedback and if clicked again it results in an error. This is likely a WebGME issue.

**Comment by brollb** [comment]
https://github.com/webgme/webgme/issues/1015

**Comment by brollb** [comment]
Fixed in webgme v2.2.0 https://github.com/webgme/webgme/pull/1048
