### ISSUE TITLE
Error when deleting connections to Operation when pivoting there from Pipeline View

### ISSUE THREAD

**Issue by JimnyCricket** [dfst/deepforge#244]
Currently throws an error when trying to delete connections to an operation when pivoting to the operation via the Pipeline View.

**Comment by JimnyCricket** [comment]
It works if you go to the Operation View and delete it there.

**Comment by brollb** [comment]
Fixed as of https://github.com/dfst/deepforge/commit/65e938f489be863bedbbccfb8cf83d049bdd6079
