### ISSUE TITLE
Color codes are printed in the terminal viewer

### ISSUE THREAD

**Issue by JimnyCricket** [dfst/deepforge#306]
When printing a scalar value (20) the color codes around it are also printed. 

```
[0m
############### Running "Print" Operation ############### [0m
[0;36m20[0m
[0m############### "Print" Operation Complete! ###############[0m
```

**Comment by brollb** [comment]
@JimnyCricket Can you put a breakpoint at https://github.com/dfst/deepforge/blob/master/src/visualizers/widgets/LogViewer/LogViewerWidget.js#L28 and get the value of
```javascript
JSON.stringify(desc.text)
```
when viewing the job with the given logs? I would like to verify that the escape codes start with the escape key
