### ISSUE TITLE
Scroll to bottom in Terminal View

### ISSUE THREAD

**Issue by JimnyCricket** [dfst/deepforge#319]
It would be nice to have the execution scroll to the bottom of the terminal when it is displayed. This will likely require a little bit of nuance, because we would also likely only want to do this if they are already at the bottom of the terminal (i.e. we wouldn't want to keep them at the bottom of the terminal if they are scrolling up through the history)

**Comment by brollb** [comment]
Fixed as of https://github.com/dfst/deepforge/commit/fee584cfde1a93d74f52786ebd1c8f86c994df08
