### ISSUE TITLE
Cannot read property of 'x' when going to graph view

### ISSUE THREAD

**Issue by JimnyCricket** [dfst/deepforge#663]
`nv.d3.js:6476 Uncaught TypeError: Cannot read property 'x' of undefinedl @ nv.d3.js:6476a.interactiveBisect @ nv.d3.js:478(anonymous function) @ nv.d3.js:6980(anonymous function) @ nv.d3.js:6974e @ GraphVizWidget.Zoom.js:76m @ nv.d3.js:319(anonymous function) @ GraphVizWidget.Zoom.js:76
debug.js:118 gme:client:WebSocket BRANCH_HASH_UPDATED event +966ms Object {metadata: Object}`

**Comment by brollb** [comment]
It looks like the graph is getting bad data to graph. The data is retrieved for the graph [here](https://github.com/dfst/deepforge/blob/master/src/visualizers/widgets/LineGraph/LineGraphWidget.js#L71) and the `lineData` object should only be populated by `line` objects (https://github.com/dfst/deepforge/blob/master/src/visualizers/widgets/LineGraph/LineGraphWidget.js#L78)... I suspect this means that the "Line" object has some bad values for points

Can you switch to the `DefaultLayout` and go to the given Graph object and check out the "Line" objects inside it? Specifically, can you check out their `points` attribute?
