### ISSUE TITLE
Image Displayed twice

### ISSUE THREAD

**Issue by JimnyCricket** [dfst/deepforge#774]
When using the deepforge.image function the image is displayed twice: 
<img width="684" alt="screen shot 2016-08-31 at 3 44 06 pm" src="https://cloud.githubusercontent.com/assets/10526094/18145664/c8218aa2-6f91-11e6-8bac-f4f293634c2e.png">

**Comment by brollb** [comment]
I think this is a specific case of #633

**Comment by brollb** [comment]
Fixed as of https://github.com/dfst/deepforge/commit/3a8108b321fe39e14ac9af8c92ee8f78acdf5b86 (in #812)
