### ISSUE TITLE
Creating a new Criterion should default to nn.Criterion

### ISSUE THREAD

**Issue by JimnyCricket** [dfst/deepforge#776]
Currently any new layer or criterion defaults to nn.Module and a criterion should default to nn.Criterion .

**Comment by JimnyCricket** [comment]
Additionally, how do you pass arguments to criterions?

**Comment by brollb** [comment]
Unfortunately there isn't a good way right now if you are using them as simply a criterion reference. You should be able to put them in an architecture for the time being and reference the arch as a work around (though it is not ideal)

**Comment by JimnyCricket** [comment]
I don't think that will work, unfortunately. Mainly because an architecture takes 1 argument and a criterion takes 2 on forward prop. Right now I'm just defining it locally.

**Comment by brollb** [comment]
good point. yeah, then you will just have to use it in the op for now :/ not ideal but should be effective for now.

Custom layers (including criterion) are available in the operation code so there shouldn't be any problems there
