### ISSUE TITLE
Worker continues to run execution when cancel pressed

### ISSUE THREAD

**Issue by SeanNaren** [dfst/deepforge#820]
The worker continued to run an execution after it was cancelled. Not entirely sure how to replicate this but suspicions is I hit the cancel button before the execution started!

**Comment by JimnyCricket** [comment]
I'm having this issue as well. 

Additionally, I often lose the connection between the worker feedback and the server (this might already be an issue). I can view the worker log and see that it is still running.

**Comment by JimnyCricket** [comment]
Looks like the same as #783

**Comment by brollb** [comment]
Did you cancel the pipeline execution or the job? I was just able to replicate the quickly canceling the pipeline execution after starting it. I was still able to cancel the job by opening it and canceling it from there.

It that is the same problem you had, canceling the job might be a temporary workaround until I straighten out the main issue.
